Repository pactus-project/pactus-gui-widgetbook, pull requests merged in 2025-01, with the labels that each got.

#2 initial Flutter project setup with base app, dependencies, and documentation updates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor_request.md
  .github/workflows/ci.yml
  .gitignore
  .metadata
  CHANGELOG.md
  CONTRIBUTING.md
  LICENSE
  README.md
  analysis_options.yaml
  assets/fonts/Inter-Black.ttf
  assets/fonts/Inter-Bold.ttf
  assets/fonts/Inter-ExtraBold.ttf
  assets/fonts/Inter-ExtraLight.ttf
  assets/fonts/Inter-Light.ttf
  assets/fonts/Inter-Medium.ttf
  assets/fonts/Inter-Regular.ttf
  assets/fonts/Inter-SemiBold.ttf
  assets/fonts/Inter-Thin.ttf
  build_runner.sh
  lib/main.dart
  lib/src/core/utils/gen/assets/assets.gen.dart
  lib/src/core/utils/gen/assets/fonts.gen.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
  web/favicon.png
  web/icons/Icon-192.png
  web/icons/Icon-512.png
  web/icons/Icon-maskable-192.png
  web/icons/Icon-maskable-512.png
  web/index.html
  web/manifest.json
Labels: feature

#5 feat: integrate `Widget Book` with a sample button code #3
  lib/app_scaffold.dart
  lib/main.dart
  lib/main.directories.g.dart
  lib/src/core/enum/button_icon_state_enum.dart
  lib/src/core/pallets/on_surface_pallet.dart
  lib/src/core/pallets/surface_pallet.dart
  lib/src/core/text_styles/inter_text_styles.dart
  lib/src/core/theme/app_theme.dart
  lib/src/core/theme/app_theme_data.dart
  lib/src/features/widgets/custom_button/custom_button_usecase.dart
  lib/src/features/widgets/custom_button/custom_button_widget.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: enhancement

#8 feat: add `l10n` localization and set configuration
  .github/workflows/ci.yml
  CHANGELOG.md
  build_runner.sh
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/main.dart
  lib/src/core/theme/app_theme.dart
  lib/src/core/theme/app_theme_data.dart
  lib/src/core/utils/gen/localization/app_locales.dart
  lib/src/core/utils/gen/localization/codegen_loader.dart
  lib/src/core/utils/gen/localization/customized_localization_addon.dart
  lib/src/core/utils/gen/localization/locale_keys.dart
  lib/src/core/utils/gen/localization/translations_utils.dart
  lib/src/features/main/language/core/language_constants.dart
  lib/src/features/main/language/core/localization_extension.dart
  lib/src/features/main/language/data/language_case.dart
  lib/src/features/widgets/custom_button/custom_button_widget.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: feature

#9 chore: add/create a barrel exports file for app styles
  lib/app_styles.dart
Labels: enhancement

#12 feat: add/create a `CustomTextWidget` for checking different modes of `InterTextStyles`
  CHANGELOG.md
  lib/app_scaffold.dart
  lib/main.dart
  lib/main.directories.g.dart
  lib/src/features/widgets/custom_text/custom_text_usecase.dart
  lib/src/features/widgets/custom_text/custom_text_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#10 feat: integrate Widget Book with counter widget (#4)
  .github/workflows/release.yml
  lib/main.directories.g.dart
  lib/src/features/widgets/counter/counter_usecase.dart
  lib/src/features/widgets/counter/counter_widget.dart
Labels: ci-cd

#19 refactor: update `InterTextStyles` according new updates in Figma design
  CHANGELOG.md
  lib/src/core/text_styles/inter_text_styles.dart
  lib/src/core/theme/app_theme_data.dart
  lib/src/features/widgets/custom_text/custom_text_usecase.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor

#17 docs: update `ReadMe.md` file according to new changes of Pactus Gui WidgetBook
  CONTRIBUTING.md
  README.md
Labels: documentation
