Repository pactus-project/pactus-gui-widgetbook, pull requests merged in 2025-04, with the labels that each got.

#35 feat: add adaptive text button
  CHANGELOG.md
  lib/app_widgets.dart
  lib/main.directories.g.dart
  lib/src/features/widgets/buttons/adaptive_primary_button/adaptive_primary_button.dart
  lib/src/features/widgets/buttons/adaptive_text_button/adaptive_text_button.dart
  lib/src/features/widgets/buttons/adaptive_text_button/adaptive_text_button_usecase.dart
  pubspec.yaml
  test/features/widgets/buttons/adaptive_text_button/adaptive_text_button_test.dart
Labels: feature

#36 fix: correct color of icons in text buttons which has icons
  CHANGELOG.md
  lib/src/features/widgets/buttons/adaptive_text_button/adaptive_text_button.dart
  pubspec.yaml
Labels: refactor

#38 fix: complete FluentApp configs with null-safe translations
  CHANGELOG.md
  lib/main.dart
  lib/src/features/main/language/core/localization_extension.dart
  lib/src/features/widgets/buttons/adaptive_primary_button/adaptive_primary_button_usecase.dart
  lib/src/features/widgets/buttons/adaptive_secondary_button/adaptive_secondary_button_usecase.dart
  lib/src/features/widgets/buttons/adaptive_text_button/adaptive_text_button.dart
  lib/src/features/widgets/buttons/adaptive_text_button/adaptive_text_button_usecase.dart
  lib/src/features/widgets/buttons/core/common/widgets/adaptive_button_content_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#40 update(buttons): add properties to button widgets
  CHANGELOG.md
  lib/src/features/widgets/buttons/adaptive_primary_button/adaptive_primary_button.dart
  lib/src/features/widgets/buttons/adaptive_primary_button/adaptive_primary_button_usecase.dart
  lib/src/features/widgets/buttons/adaptive_secondary_button/adaptive_secondary_button.dart
  lib/src/features/widgets/buttons/adaptive_secondary_button/adaptive_secondary_button_usecase.dart
  lib/src/features/widgets/buttons/adaptive_text_button/adaptive_text_button.dart
  lib/src/features/widgets/buttons/adaptive_text_button/adaptive_text_button_usecase.dart
  lib/src/features/widgets/buttons/core/common/widgets/adaptive_button_content_widget.dart
  lib/src/features/widgets/buttons/core/utils/methods/get_fluent_button_style_method.dart
  lib/src/features/widgets/buttons/core/utils/methods/get_fluent_outlined_button_style_method.dart
  pubspec.yaml
Labels: feature

#42 refactor(core): remove height property from text styles
  CHANGELOG.md
  lib/src/core/text_styles/inter_text_styles.dart
  pubspec.yaml
Labels: enhancement

#43 refactor: update all text styles to height 1.0
  CHANGELOG.md
  lib/src/core/text_styles/inter_text_styles.dart
  pubspec.yaml
Labels: enhancement

#46 Refactor/fix scaffold background color
  CHANGELOG.md
  lib/src/core/pallets/colors/app_colors.dart
  lib/src/core/text_styles/inter_text_styles.dart
  lib/src/core/theme/app_theme_data.dart
  lib/src/features/widgets/buttons/adaptive_text_button/adaptive_text_button.dart
  lib/src/features/widgets/buttons/core/utils/methods/get_fluent_button_style_method.dart
  lib/src/features/widgets/buttons/core/utils/methods/get_fluent_outlined_button_style_method.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor

#48 feat(chipTextBox): improve text readability with updated color scheme
  CHANGELOG.md
  lib/app_styles.dart
  lib/src/core/enum/chip_text_mode.dart
  lib/src/core/enum/pallet_colors_enum.dart
  lib/src/core/extensions/color_context_extension.dart
  lib/src/core/pallets/blue_pallet.dart
  lib/src/core/pallets/dark_pallet.dart
  lib/src/core/pallets/green_pallet.dart
  lib/src/core/pallets/pane_pallet.dart
  lib/src/core/pallets/red_pallet.dart
  lib/src/core/pallets/seed_pallet.dart
  lib/src/core/theme/app_theme_data.dart
  lib/src/features/widgets/chip_text_box/chip_text_box_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feature
